version: '3'
services:
  dev:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    stdin_open: true
    command: npm start